pipeline:
  name: hello-world-java-helm-pipeline
  identifier: helloworldjavahelmpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
      - stage:
          name: hello-world-java-service-helm
          identifier: helloworldjavaservicehelm
          tags: {}
          template:
            templateRef: HelloWorldHelmTemplate
            versionLabel: v1
            templateInputs:
              # Use the HelmDeployment type for Helm charts
              type: Deployment
              spec:
                service:
                  serviceInputs:
                    serviceDefinition:
                      # Use Helm instead of Kubernetes
                      type: NativeHelm
                      spec:
                        artifacts:
                          primary:
                            primaryArtifactRef: <+input>
                            sources: <+input>
                        variables:
                          - name: tag
                            type: String
                            # Fetch the tag value dynamically using the service variables
                            value: <+input>
