apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-java
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
        - name: hello-world-java
          image: docker.io/prasaddasari/hello-world-java:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
